const fs = require("fs");
const path = require("path");
const { withAndroidManifest, withDangerousMod, AndroidConfig } = require("expo/config-plugins");

/**
 * Teach Android to trust VK's TLS chain on old devices.
 *
 * *.vk.com is issued by "GTS WR1", which chains to "GTS Root R1". VK's servers
 * send only the leaf and WR1 — not the GlobalSign cross-sign — so a device has
 * to already hold GTS Root R1 to build a path. Android 9's CA store predates it
 * (137 roots, zero from Google Trust Services), so every request to vk.com,
 * id.vk.com, oauth.vk.com and api.vk.com fails with
 * `SSL error: The certificate authority is not trusted` — the WebView renders a
 * blank page and the login (and the not_robot captcha before it) simply dies.
 * Verified on an Android 9 emulator: https://example.com loads, any *.vk.com
 * page does not.
 *
 * This bundles the genuine, public GTS Root R1 (SHA-256
 * D9:47:43:2A:BD:E7:B7:FA:90:FC:2E:6B:59:10:1B:12:80:E0:E1:C7:E4:E4:0F:A3:C6:88:7F:FF:57:A7:F4:CF,
 * valid to 2036) and adds it as a trust anchor **for vk.com and vk.ru only**,
 * alongside — not instead of — the system anchors. Certificate validation stays
 * fully on: this adds a missing real root, it does not weaken or bypass any
 * check, and no other host is affected.
 *
 * VK's media CDN (*.userapi.com, vkuseraudio.net) needs nothing here: that chain
 * ships a cross-signed root that terminates in "Hellenic Academic and Research
 * Institutions RootCA 2015", which Android 9 does have.
 */

const CERT_RES_NAME = "gts_root_r1";
const XML_RES_NAME = "network_security_config";

const NETWORK_SECURITY_CONFIG = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withVkTrustAnchor.js — do not edit by hand. -->
<network-security-config>
    <domain-config>
        <domain includeSubdomains="true">vk.com</domain>
        <domain includeSubdomains="true">vk.ru</domain>
        <trust-anchors>
            <certificates src="system" />
            <certificates src="@raw/${CERT_RES_NAME}" />
        </trust-anchors>
    </domain-config>
</network-security-config>
`;

const withVkTrustAnchorFiles = (config) =>
  withDangerousMod(config, [
    "android",
    async (cfg) => {
      const res = path.join(cfg.modRequest.platformProjectRoot, "app", "src", "main", "res");
      const raw = path.join(res, "raw");
      const xml = path.join(res, "xml");
      fs.mkdirSync(raw, { recursive: true });
      fs.mkdirSync(xml, { recursive: true });

      const source = path.join(__dirname, "certs", "gts_root_r1.pem");
      // Fail loudly: a silently missing anchor would look exactly like the bug
      // this plugin exists to fix, only now with no error to go on.
      if (!fs.existsSync(source)) {
        throw new Error(`withVkTrustAnchor: missing certificate at ${source}`);
      }
      fs.copyFileSync(source, path.join(raw, `${CERT_RES_NAME}.pem`));
      fs.writeFileSync(path.join(xml, `${XML_RES_NAME}.xml`), NETWORK_SECURITY_CONFIG);
      return cfg;
    },
  ]);

const withVkTrustAnchorManifest = (config) =>
  withAndroidManifest(config, (cfg) => {
    const app = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults);
    app.$["android:networkSecurityConfig"] = `@xml/${XML_RES_NAME}`;
    return cfg;
  });

module.exports = (config) => withVkTrustAnchorManifest(withVkTrustAnchorFiles(config));
