const fs = require("fs");
const path = require("path");
const { withAndroidManifest, withDangerousMod, AndroidConfig } = require("expo/config-plugins");

/**
 * Teach Android to trust VK's TLS chain on old devices.
 *
 * *.vk.com is issued by "GTS WR1", which chains to "GTS Root R1". VK's servers
 * send only the leaf and WR1 — not the GlobalSign cross-sign — so a device has
 * to already hold GTS Root R1 to build a path. Android 9's CA store predates it
 * (137 roots, zero from Google Trust Services), so every request to vk.com,
 * id.vk.com, oauth.vk.com and api.vk.com fails with
 * `SSL error: The certificate authority is not trusted` — the WebView renders a
 * blank page and the login (and the not_robot captcha before it) simply dies.
 * Verified on an Android 9 emulator: https://example.com loads, any *.vk.com
 * page does not.
 *
 * This bundles the genuine, public GTS Root R1 (SHA-256
 * D9:47:43:2A:BD:E7:B7:FA:90:FC:2E:6B:59:10:1B:12:80:E0:E1:C7:E4:E4:0F:A3:C6:88:7F:FF:57:A7:F4:CF,
 * valid to 2036) and adds it as a trust anchor **for vk.com and vk.ru only**,
 * alongside — not instead of — the system anchors. Certificate validation stays
 * fully on: this adds a missing real root, it does not weaken or bypass any
 * check, and no other host is affected.
 *
 * VK's media CDN (*.userapi.com, vkuseraudio.net) needs nothing here: that chain
 * ships a cross-signed root that terminates in "Hellenic Academic and Research
 * Institutions RootCA 2015", which Android 9 does have.
 */

const CERT_RES_NAME = "gts_root_r1";
const XML_RES_NAME = "network_security_config";

// The cert is INLINED, not read from a file. A .pem on disk is matched by the
// repo's `*.pem` gitignore, and EAS builds the project tarball honouring
// .gitignore, so the file is dropped and prebuild dies with
// "withVkTrustAnchor: missing certificate". Inlining the (public) root removes
// that failure mode entirely — there is nothing for an ignore rule to exclude.
// GTS Root R1, SHA-256 D9:47:43:2A:BD:E7:B7:FA:90:FC:2E:6B:59:10:1B:12:80:E0:E1:
// C7:E4:E4:0F:A3:C6:88:7F:FF:57:A7:F4:CF, valid to 2036.
const GTS_ROOT_R1_PEM = `-----BEGIN CERTIFICATE-----
MIIFVzCCAz+gAwIBAgINAgPlk28xsBNJiGuiFzANBgkqhkiG9w0BAQwFADBHMQsw
CQYDVQQGEwJVUzEiMCAGA1UEChMZR29vZ2xlIFRydXN0IFNlcnZpY2VzIExMQzEU
MBIGA1UEAxMLR1RTIFJvb3QgUjEwHhcNMTYwNjIyMDAwMDAwWhcNMzYwNjIyMDAw
MDAwWjBHMQswCQYDVQQGEwJVUzEiMCAGA1UEChMZR29vZ2xlIFRydXN0IFNlcnZp
Y2VzIExMQzEUMBIGA1UEAxMLR1RTIFJvb3QgUjEwggIiMA0GCSqGSIb3DQEBAQUA
A4ICDwAwggIKAoICAQC2EQKLHuOhd5s73L+UPreVp0A8of2C+X0yBoJx9vaMf/vo
27xqLpeXo4xL+Sv2sfnOhB2x+cWX3u+58qPpvBKJXqeqUqv4IyfLpLGcY9vXmX7w
Cl7raKb0xlpHDU0QM+NOsROjyBhsS+z8CZDfnWQpJSMHobTSPS5g4M/SCYe7zUjw
TcLCeoiKu7rPWRnWr4+wB7CeMfGCwcDfLqZtbBkOtdh+JhpFAz2weaSUKK0Pfybl
qAj+lug8aJRT7oM6iCsVlgmy4HqMLnXWnOunVmSPlk9orj2XwoSPwLxAwAtcvfaH
szVsrBhQf4TgTM2S0yDpM7xSma8ytSmzJSq0SPly4cpk9+aCEI3oncKKiPo4Zor8
Y/kB+Xj9e1x3+naH+uzfsQ55lVe0vSbv1gHR6xYKu44LtcXFilWr06zqkUspzBmk
MiVOKvFlRNACzqrOSbTqn3yDsEB750Orp2yjj32JgfpMpf/VjsPOS+C12LOORc92
wO1AK/1TD7Cn1TsNsYqiA94xrcx36m97PtbfkSIS5r762DL8EGMUUXLeXdYWk70p
aDPvOmbsB4om3xPXV2V4J95eSRQAogB/mqghtqmxlbCluQ0WEdrHbEg8QOB+DVrN
VjzRlwW5y0vtOUucxD/SVRNuJLDWcfr0wbrM7Rv1/oFB2ACYPTrIrnqYNxgFlQID
AQABo0IwQDAOBgNVHQ8BAf8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4E
FgQU5K8rJnEaK0gnhS9SZizv8IkTcT4wDQYJKoZIhvcNAQEMBQADggIBAJ+qQibb
C5u+/x6Wki4+omVKapi6Ist9wTrYggoGxval3sBOh2Z5ofmmWJyq+bXmYOfg6LEe
QkEzCzc9zolwFcq1JKjPa7XSQCGYzyI0zzvFIoTgxQ6KfF2I5DUkzps+GlQebtuy
h6f88/qBVRRiClmpIgUxPoLW7ttXNLwzldMXG+gnoot7TiYaelpkttGsN/H9oPM4
7HLwEXWdyzRSjeZ2axfG34arJ45JK3VmgRAhpuo+9K4l/3wV3s6MJT/KYnAK9y8J
ZgfIPxz88NtFMN9iiMG1D53Dn0reWVlHxYciNuaCp+0KueIHoI17eko8cdLiA6Ef
MgfdG+RCzgwARWGAtQsgWSl4vflVy2PFPEz0tv/bal8xa5meLMFrUKTX5hgUvYU/
Z6tGn6D/Qqc6f1zLXbBwHSs09dR2CQzreExZBfMzQsNhFRAbd03OIozUhfJFfbdT
6u9AWpQKXCBfTkBdYiJ23//OYb2MI3jSNwLgjt7RETeJ9r/tSQdirpLsQBqvFAnZ
0E6yove+7u7Y/9waLd64NnHi/Hm3lCXRSHNboTXns5lndcEZOitHTtNCjv0xyBZm
2tIMPNuzjsmhDYAPexZ3FL//2wmUspO8IFgV6dtxQ/PeEMMA3KgqlbbC1j+Qa3bb
bP6MvPJwNQzcmRk13NfIRmPVNnGuV/u3gm3c
-----END CERTIFICATE-----
`;

const NETWORK_SECURITY_CONFIG = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withVkTrustAnchor.js — do not edit by hand. -->
<network-security-config>
    <domain-config>
        <domain includeSubdomains="true">vk.com</domain>
        <domain includeSubdomains="true">vk.ru</domain>
        <trust-anchors>
            <certificates src="system" />
            <certificates src="@raw/${CERT_RES_NAME}" />
        </trust-anchors>
    </domain-config>
</network-security-config>
`;

const withVkTrustAnchorFiles = (config) =>
  withDangerousMod(config, [
    "android",
    async (cfg) => {
      const res = path.join(cfg.modRequest.platformProjectRoot, "app", "src", "main", "res");
      const raw = path.join(res, "raw");
      const xml = path.join(res, "xml");
      fs.mkdirSync(raw, { recursive: true });
      fs.mkdirSync(xml, { recursive: true });

      fs.writeFileSync(path.join(raw, `${CERT_RES_NAME}.pem`), GTS_ROOT_R1_PEM);
      fs.writeFileSync(path.join(xml, `${XML_RES_NAME}.xml`), NETWORK_SECURITY_CONFIG);
      return cfg;
    },
  ]);

const withVkTrustAnchorManifest = (config) =>
  withAndroidManifest(config, (cfg) => {
    const app = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults);
    app.$["android:networkSecurityConfig"] = `@xml/${XML_RES_NAME}`;
    return cfg;
  });

module.exports = (config) => withVkTrustAnchorManifest(withVkTrustAnchorFiles(config));
