name: Check any push before merge

on:
  workflow_call:
    secrets:
      EXPO_TOKEN:
        required: true
      GOOGLE_PLAY_SERVICE_ACCOUNT_JSON:
        required: true
    inputs:
      DOMAIN:
        required: true
        type: string

jobs:
  check-config:
    runs-on: ubuntu-latest
    #runs-on: main-n
    steps:
      - name: Check required config
        run: |
          [[ -z "${{ secrets.EXPO_TOKEN }}" ]] && echo "❌ Missing secrets.EXPO_TOKEN" && exit 1
          [[ -z "${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}" ]] && echo "❌ Missing secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON" && exit 1
          echo "✅ All required secrets and vars are set"

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: ${{ github.ref_name }}
      - name: Cleanup workspace
        if: always()
        run: |
          echo "🧹 Cleaning up workspace files..."
          find . -mindepth 1 -delete