name: Check any push before merge

on:
  workflow_call:
    secrets:
      EXPO_TOKEN:
        required: true
    inputs:
      DOMAIN:
        required: true
        type: string

jobs:
  check-config:
    runs-on: ubuntu-latest
    steps:
      - name: Check required config
        run: |
          [[ -z "${{ secrets.EXPO_TOKEN }}" ]] && echo "❌ Missing secrets.EXPO_TOKEN" && exit 1
          echo "✅ All required secrets and vars are set"
