---
name: Merge or push to default_branch

on:
  push:
    branches:
      - main

jobs:
  validate:
    uses: ./.github/workflows/check.yml
    secrets:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      GOOGLE_PLAY_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
    with:
      DOMAIN: ${{ vars.DOMAIN }}
<<<<<<< 15-add-github-actions
  test:
    uses: ./.github/workflows/test.yml
  main:
    needs:
      - test
=======
<<<<<<< 15-add-github-actions
  wait-for-unlock:
    uses: ./.github/workflows/wait-for-unlock.yml
  main:
    needs:
      - wait-for-unlock
>>>>>>> main
      - validate
    #if: |
    #  (github.event_name == 'push' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)) ||
    #  (github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.base_ref == github.event.repository.default_branch && github.head_ref != github.base_ref)
    runs-on: ubuntu-latest
    #runs-on: main-n
<<<<<<< 15-add-github-actions
=======
=======
  bump-prepatch:
    needs: validate
    if: ${{ (github.event_name == 'push' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)) ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.base_ref == github.event.repository.default_branch) }}
    #runs-on: ubuntu-latest
    runs-on: main-n
>>>>>>> main
>>>>>>> main
    permissions:
      contents: write
    steps:
      - name: Lock workspace
        if: always()
        run: |
          echo "${{ github.job }}@${{ github.run_id }}" > "${GITHUB_WORKSPACE}/.runner.lock"
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: ${{ github.event.repository.default_branch }}
      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "318709+neoff@users.noreply.github.com"
          git config init.defaultBranch ${{ github.event.repository.default_branch }}

      - name: Get version from package.json
        id: version
        run: |
          version=$(node -p "require('./package.json').version")
          echo "current=$version"
          echo "current=$version" >> $GITHUB_OUTPUT

      - name: Bump Version
        id: bump
        uses: cbrgm/semver-bump-action@main
        with:
          current-version: ${{ steps.version.outputs.current }}
          bump-level: prerelease
          prerelease-tag: "alpha"
      #- name: Update iOS Info.plist version
      #  run: |
      #    plist="ios/visky/Info.plist"
      #    version="${{ steps.bump.outputs.new_version }}"
      #    build_number=$(date +%s)  # можно использовать счетчик или date
      #    /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $version" $plist
      #    /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $build_number" $plist
      #    git add $plist
      #- name: Update Android build.gradle
      #  run: |
      #    version="${{ steps.bump.outputs.new_version }}"
      #    code=$(date +%s)
      #    sed -i.bak -E "s/versionName \".*\"/versionName \"$version\"/" android/app/build.gradle
      #    sed -i.bak -E "s/versionCode [0-9]+/versionCode $code/" android/app/build.gradle
      #    git add android/app/build.gradle
      - name: Bump patch version if not release-related
        run: |
          version="${{ steps.bump.outputs.new_version }}"
          jq '.expo.version = "'$version'"' app.json > tmp.$$.json && mv tmp.$$.json app.json
          npm version "${{ steps.bump.outputs.new_version }}" --no-git-tag-version
          git add package.json app.json
          git commit -m "chore(#0): bump patch version to ${{ steps.bump.outputs.new_version }}"
          git push origin ${{ github.event.repository.default_branch }}

      - name: Unlock workspace
        if: always()
        run: |
          rm -f "${GITHUB_WORKSPACE}/.runner.lock"
      - name: Cleanup workspace
        if: always()
        run: |
          echo "🧹 Cleaning up workspace files..."
          find . -mindepth 1 -delete
...
