---
name: Push application image

on:
  workflow_run:
    workflows: ["Create release branch"]
    types:
      - completed
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch or tag to deploy (example: main, 1.4.0)'
        required: true
        type: string

jobs:
  wait-for-unlock:
    uses: ./.github/workflows/wait-for-unlock.yml
  validate:
    uses: ./.github/workflows/check.yml
    secrets:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      GOOGLE_PLAY_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
    with:
      DOMAIN: ${{ vars.DOMAIN }}
  build-publish:
    name: Build and publish Docker image
    if: (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    #runs-on: mini-s
    needs:
      - validate
    permissions:
      actions: read
      contents: read

    steps:
      - name: Lock workspace
        if: always()
        run: |
          echo "${{ github.job }}@${{ github.run_id }}" > "${GITHUB_WORKSPACE}/.runner.lock"

      - name: Download artifact from previous workflow
        if: github.event_name == 'workflow_run'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          run_id=${{ github.event.workflow_run.id }}
          echo "Getting artifacts for run $run_id"

          artifact_url=$(gh api \
            repos/${{ github.repository }}/actions/runs/$run_id/artifacts \
            --jq '.artifacts[] | select(.name=="branch-name") | .archive_download_url')

          echo "Found artifact: $artifact_url"

          curl -L -H "Authorization: token $GH_TOKEN" -o artifact.zip "$artifact_url"
          unzip -o artifact.zip

      - name: Read branch
        if: github.event_name == 'workflow_run'
        id: read_branch
        run: |
          branch=$(cat branch.txt)
          echo "branch=$branch" >> $GITHUB_OUTPUT
      

      - name: Checkout repository workflow_dispatch
        if: github.event_name == 'workflow_dispatch'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: ${{ github.event.inputs.ref }}
      - name: Checkout repository workflow_run
        if: github.event_name == 'workflow_run'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: ${{ steps.read_branch.outputs.branch }}

      - name: Get current version
        id: version
        run: |
          current_version=$(node -p "require('./package.json').version")
          code_version=$(node -p "require('./app.json').expo.android.versionCode")
          app_code_version=$(node -p "require('./app.json').expo.version")
          echo "Current version: $current_version"
          echo "current=$current_version" >> $GITHUB_OUTPUT

      - name: Get current code version
        id: code_version
        run: |
          current_version=$(node -p "require('./package.json').version")
          code_version=$(node -p "require('./app.json').expo.android.versionCode")
          app_code_version=$(node -p "require('./app.json').expo.version")
          echo "Current version: $current_version"
          echo "current=$code_version" >> $GITHUB_OUTPUT

      - name: Build Android with Expo EAS
        run: |
          yarn install
          yarn test && EXPO_TOKEN=${EAS_ACCESS_TOKEN} yarn build:cloud
        env:
          EAS_ACCESS_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Build Android local Expo EAS
        if: ${{ vars.BUILD_LOCAL == 'truees'}}
        run: |
          yarn install
          yarn test && EXPO_TOKEN=${EAS_ACCESS_TOKEN} yarn eas build --platform android --local --profile preview --non-interactive --output android/build/visky-${{ steps.version.outputs.current }}-${{ steps.code_version.outputs.current }}.apk
        env:
          EAS_ACCESS_TOKEN: ${{ secrets.EXPO_TOKEN }}


      - name: Set up eas
        if: ${{ vars.BUILD_LOCAL == 'true'}}
        run: |
          mkdir -p ~/.credentials
          echo "${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}" | base64 --decode > ~/.credentials/google-play-service-account.json

      - name: Upload Android with Expo EAS
        if: ${{ vars.BUILD_LOCAL == 'true'}}
        run: |
          yarn install
          EXPO_TOKEN=${EAS_ACCESS_TOKEN} yarn eas submit --platform android --profile preview --path android/build/visky-${{ steps.version.outputs.current }}-${{ steps.code_version.outputs.current }}.apk
          EXPO_TOKEN=${EAS_ACCESS_TOKEN} yarn build
        env:
          EAS_ACCESS_TOKEN: ${{ secrets.EXPO_TOKEN }}

      #- name: Build iOS with Expo EAS
      #  run: |
      #    npm install -g eas-cli
      #    eas build -p ios --profile preview --non-interactive
      #  env:
      #    EAS_ACCESS_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Upload tag name
        uses: actions/upload-artifact@v4
        with:
          name: branch-name
          path: branch.txt

      - name: Unlock workspace
        if: always()
        run: |
          rm -f "${GITHUB_WORKSPACE}/.runner.lock"
      - name: Cleanup workspace
        if: always()
        run: |
          echo "🧹 Cleaning up workspace files..."
          find . -mindepth 1 -delete
...