---
name: Create release branch

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type (minor or major)'
        required: true
        default: 'minor'
        type: choice
        options:
          - minor
          - major
  push:
    branches:
      - 'release/**'
  pull_request:
    types: [closed]
    branches:
      - 'release/**'
    #paths:
    #  - 'src/**'
    #  - 'Dockerfile'

jobs:
  relese:
    if: |
      ((github.event_name == 'push' 
            || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)) 
        && startsWith(github.ref, 'refs/heads/release/')) 
      || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}

    steps:
      - name: Set up bump type
        run: |
          echo "RELEASE_TYPE=${{ github.event.inputs.release_type }}" >> $GITHUB_ENV
      - name: Set up bump type patch
        if: |
          (github.event_name == 'push' 
                || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)) 
            && startsWith(github.ref, 'refs/heads/release/')
        run: |
          echo "RELEASE_TYPE=patch" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: ${{ github.ref_name }}
      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git config init.defaultBranch ${{ github.event.repository.default_branch }}

      - name: Get current version
        id: version
        run: |
          current_version=$(node -p "require('./package.json').version")
          echo "Current version: $current_version"
          echo "current=$current_version" >> $GITHUB_OUTPUT

      #https://github.com/marketplace/actions/semver-bump-action
      - name: Bump Version
        id: bump
        uses: cbrgm/semver-bump-action@main
        with:
          current-version: ${{ steps.version.outputs.current }}
          bump-level: ${{ env.RELEASE_TYPE }}

      - name: Push changes and tags
        id: release
        env:
          workflow_event: ${{ github.event_name }}
          type: ${{ env.RELEASE_TYPE }}
          current: ${{ steps.version.outputs.current }}
          next_version: ${{ steps.bump.outputs.new_version }}
        run: |
          IFS='.' read -r major minor patch <<< "${next_version}"
          if [[ ${workflow_event} == 'workflow_dispatch' && ${type} != 'major' ]]; then
            IFS='.' read -r major_ minor patch_ <<< "${current}"
          fi
          tag="${major}.${minor}.${patch}"
          echo "Release: $tag"
          release_branch="release/$major.$minor"
          git checkout "$release_branch" 2>/dev/null || git checkout -b "$release_branch"
          
          if [ $next_version != $tag ]; then
            echo "Version mismatch: $next_version != $tag"
          fi
          code_version=$(node -p "require('./app.json').expo.android.versionCode")
          code=$(node -e "const fs = require('fs'); const app = require('./app.json'); app.expo.android.versionCode = (app.expo.android.versionCode || 1) + 1; fs.writeFileSync('app.json', JSON.stringify(app, null, 2));")
          npm version "$tag" --no-git-tag-version
          jq '.expo.version = "'$tag'" | .expo.android.versionCode += 1' app.json > tmp.$$.json && mv tmp.$$.json app.json
          git add package.json app.json
          
          git commit -a -m "release: $tag"
          git tag -a "$tag" -m "release: $tag"
          git push origin "$release_branch"
          git push origin "refs/tags/$tag"
          
          echo "release/$major.$minor" > branch.txt
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: Upload branch name
        uses: actions/upload-artifact@v4
        with:
          name: branch-name
          path: branch.txt

      - name: Bump release version
        if: github.event_name == 'workflow_dispatch'
        id: bump-release
        uses: cbrgm/semver-bump-action@main
        with:
          current-version: ${{ steps.release.outputs.tag }}
          bump-level: preminor
          prerelease-tag: "alpha"

      - name: Bump version in master to next development version
        if: github.event_name == 'workflow_dispatch'
        run: |
          git checkout ${{ env.DEFAULT_BRANCH }}
          
          next_version=${{ steps.bump-release.outputs.new_version }}
          code=$(node -p "require('./app.json').expo.android.versionCode")
          echo "Next development version: $next_version"
          
          npm version "$next_version" --no-git-tag-version
          jq '.expo.version = "'$next_version'" | .expo.android.versionCode = '$code'' app.json > tmp.$$.json && mv tmp.$$.json app.json
          git add package.json app.json
          
          git commit -m "chore: bump to next dev version $next_version [skip ci]"
          git push origin ${{ env.DEFAULT_BRANCH }}
          
      #Create release notes
      - name: Get Latest Tag
        id: latest_tag
        run: |
          git fetch --tags
          tag=$(git tag --sort=-v:refname | head -n 1)
          echo "current version is: $tag"
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: Get previous tag
        id: prev_tag
        run: |
          git fetch --tags
          prev=$(git tag --sort=-v:refname | sed -n '2p')
          echo "Previous tag: $prev"
          echo "prev_tag=$prev" >> $GITHUB_OUTPUT

      - name: Generate changelog
        id: changelog
        run: |
          RAW_LOG=$(git log --pretty=format:"- %s" ${{ steps.prev_tag.outputs.prev_tag }}..${{ steps.latest_tag.outputs.tag }} \
            | grep -vE '^(- )?(release: .*?|Merge remote-tracking|chore(#0): .*?)' \
            | sed '/^ *$/d')
          # Initialize sections
          FEAT=""
          FIX=""
          DOCS=""
          REFACTOR=""
          CHORE=""
          OTHER=""
      
          while IFS= read -r line; do
            case "$line" in
              feat:*) FEAT+="${line}\n" ;;
              fix:*) FIX+="${line}\n" ;;
              docs:*) DOCS+="${line}\n" ;;
              refactor:*) REFACTOR+="${line}\n" ;;
              chore:*) CHORE+="${line}\n" ;;
              *) OTHER+="${line}\n" ;;
            esac
          done <<< "$RAW_LOG"
      
          FINAL_LOG=""
      
          add_section() {
            local title="$1"
            local content="$2"
            if [ -n "$content" ]; then
            FINAL_LOG+="### $title\n"
            FINAL_LOG+="$content\n"
            fi
          }
      
          add_section "🚀 Features" "$FEAT"
          add_section "🛠️ Fixes" "$FIX"
          add_section "📝 Docs" "$DOCS"
          add_section "🧠 Refactoring" "$REFACTOR"
          add_section "🧹 Chores" "$CHORE"
          add_section "🌀 Other" "$OTHER"
      
          echo "📝 Clean grouped changelog:"
          echo -e "$FINAL_LOG"
      
          # Save to output (escaped for GitHub Actions)
          esc="${FINAL_LOG//'%'/'%25'}"
          esc="${esc//$'\n'/'%0A'}"
          esc="${esc//$'\r'/'%0D'}"
          echo "changelog=$esc" >> $GITHUB_OUTPUT

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.latest_tag.outputs.tag }}
          body: ${{ steps.changelog.outputs.changelog }}
...
