repositories:
  - name: stable
    url: https://charts.helm.sh/stable

helmDefaults:
  atomic: true
  timeout: 300

environments:
  production:
    values:
      []
---
releases:
  - name: {{ env "REPO_NAME" }}
    namespace: default
    chart: ./
    values:
      - values.yaml