replicaCount: 1
name: sandbox
appVersion: ""
version: 0.0.0

image:
  repository: ""
  tag: "latest"
  pullPolicy: Always

imagePullSecrets:
  - name: regcred

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/redirect-entry-point: https
  hosts:
    - host: envarg.com
      paths:
        - path: /
          pathType: Prefix
  issuerName: letsencrypt-prod
  tls:
    - secretName: sandbox-tls
      hosts:
        - envarg.com