name: Check any push before merge

on:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
      DOCKERHUB_EMAIL:
        required: true
      KUBECONFIG:
        required: true
    inputs:
      DOMAIN:
        required: true
        type: string

jobs:
  check-config:
    runs-on: ubuntu-latest
    steps:
      - name: Check required config
        run: |
          [[ -z "${{ vars.DOMAIN }}" ]] && echo "❌ Missing vars.DOMAIN" && exit 1
          [[ -z "${{ secrets.DOCKERHUB_USERNAME }}" ]] && echo "❌ Missing secrets.DOCKERHUB_USERNAME" && exit 1
          [[ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]] && echo "❌ Missing secrets.DOCKERHUB_TOKEN" && exit 1
          [[ -z "${{ secrets.DOCKERHUB_EMAIL }}" ]] && echo "❌ Missing secrets.DOCKERHUB_EMAIL" && exit 1
          [[ -z "${{ secrets.KUBECONFIG }}" ]] && echo "❌ Missing secrets.KUBECONFIG" && exit 1
          echo "✅ All required secrets and vars are set"
