name: Merge

on:
  push:
    branches:
      - main
      - master
      - 'release/**'


jobs:
  debug:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}

    steps:
      - name: Print environment variables
        run: |
          echo "event ${{ github.event_name }}"
          echo "github.ref ${{ github.ref }}"
      #- name: Parse semver string
      #  id: semver_parser 
      #  uses: booxmedialtd/ws-action-parse-semver@v1
      #  with:
      #    input_string: '1.0.4'
      #- name: Use parsed semver #DEPRECATION WARNING 
      #  run: |
      #        echo "v${{ steps.semver_parser.outputs.major }}"
      #        echo "v${{ steps.semver_parser.outputs.minor }}"
      #        echo "v${{ steps.semver_parser.outputs.patch }}"
      #        echo "v${{ steps.semver_parser.outputs.prerelease }}"
      #        echo "v${{ steps.semver_parser.outputs.build }}"
      #        echo "v${{ steps.semver_parser.outputs.fullversion }}"

      - name: Get current version
        id: version
        #current_version=$(node -p "require('./package.json').version")
        #current=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        run: |
          current_version='1.2.3'
          echo "Current version: $current_version"
          echo "version=$current_version" >> $GITHUB_OUTPUT

      #https://github.com/marketplace/actions/semver-bump-action
      - name: Bump Minor Version
        id: bump
        uses: cbrgm/semver-bump-action@main
        with:
          current-version: ${{ steps.version.outputs.version }}
          bump-level: minor

      - name: Output
        run: |
          new_tag=${{ steps.bump.outputs.new_version }}
          echo $new_tag

      - name: Manual bump version in master to next development version
        run: |
          current="${{ steps.version.outputs.current }}"
          IFS='.' read -r major minor patch <<< "$current"
          
          if [[ "${{ github.event.inputs.release_type }}" == "minor" ]]; then
            minor=$((minor + 1))
            patch=0
          else
            major=$((major + 1))
            minor=0
            patch=0
          fi
          
          next_version="$major.$minor.$patch"
          echo "Next development version: $next_version"

          echo "git checkout ${{ github.event.repository.default_branch }}"
          echo 'git add package.json'
          echo 'git commit -m "chore: bump to next dev version $next_version [skip ci]"''
          echo 'git push origin ${{ env.DEFAULT_BRANCH }}''

  bump-patch:
    #if: ${{ github.event_name == 'push' && github.ref_name == github.event.repository.default_branch }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          #ref: ${{ env.DEFAULT_BRANCH }}

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Check if this push follows a release branch creation
        id: release_check
        run: |
          latest_commit=$(git log -1 --pretty=%B)
          echo "Latest commit: $latest_commit"

          if echo "$latest_commit" | grep -q "bump to next dev version"; then
            echo "skip_bump=true" >> $GITHUB_OUTPUT
          else
            echo "skip_bump=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Get version from package.json
        id: version
        run: |
          version=$(node -p "require('./package.json').version")
          echo "version=$version"
          echo "version=$version" >> $GITHUB_OUTPUT
          
      - name: Bump patch version if not release-related
        if: steps.release_check.outputs.skip_bump == 'false'
        run: |
          npm version patch --no-git-tag-version
          git add package.json
          git commit -m "chore: bump patch version [skip ci]"
          git push origin ${{ env.DEFAULT_BRANCH }}
