name: Bump version on merge to release branch

on:
  workflow_dispatch:
  push:
    branches:
      - 'release/**'

jobs:
  bump-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Чтобы видеть теги

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      #- name: Bump patch version
      #  run: |
      #    npm version patch -m "chore(release): %s [skip ci]"

      - name: Push changes and tags
        run: |
          branch=${{ github.ref_name }}
          tag=$(node -p "require('./package.json').version")
          
          git push origin "$branch"
          git push origin "refs/tags/$tag"


      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version
        id: version
        run: |
          version=$(node -p "require('./package.json').version")
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        run: |
          repo_full=${{ github.repository }}
          repo_name=$(basename $repo_full)
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag ${{ secrets.DOCKERHUB_USERNAME }}/$repo_name:latest \
            --tag ${{ secrets.DOCKERHUB_USERNAME }}/$repo_name:${{ steps.version.outputs.version }} \
            --push .

