name: Bump version on merge to master

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'release/**'

jobs:
  bump-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Чтобы видеть теги

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Bump patch version
        run: |
          npm version patch -m "chore(release): %s [skip ci]"

      - name: Push changes and tags
        run: |
          git push origin HEAD:master --follow-tags

