// Auto-generated by https://github.com/vladkens/apigen-ts
// Source: https://visky.envarg.com/v3/api-docs

type Headers = Record<string, string>
export type ApigenHeaders = Headers | ((method: string, path: string) => Headers | Promise<Headers>)

export interface ApigenConfig {
	baseUrl: string
	headers: ApigenHeaders
}

export interface ApigenRequest extends Omit<RequestInit, 'body'> {
	search?: Record<string, unknown>
	body?: unknown
}

export class ApiClient {
	Config: ApigenConfig

	constructor(config?: Partial<ApigenConfig>) {
		this.Config = { baseUrl: '/', headers: {}, ...config }
	}

	async ParseError(rep: Response) {
		try {
			return await rep.json()
		} catch (e) {
			throw rep
		}
	}

	PrepareFetchUrl(path: string): URL {
		let base = this.Config.baseUrl
		if ('location' in globalThis && (base === '' || base.startsWith('/'))) {
			const { location } = globalThis as unknown as { location: { origin: string } }
			base = `${location.origin}${base.endsWith('/') ? base : `/${base}`}`
		}

		return new URL(path, base)
	}

	async Fetch<T>(method: string, path: string, opts: ApigenRequest = {}): Promise<T> {
		const url = this.PrepareFetchUrl(path)

		for (const [k, v] of Object.entries(opts?.search ?? {})) {
			url.searchParams.append(k, Array.isArray(v) ? v.join(',') : (v as string))
		}

		const configHeaders =
			typeof this.Config.headers === 'function'
				? await this.Config.headers(method, path)
				: this.Config.headers

		const headers = new Headers({ ...configHeaders, ...opts.headers })
		const ct = headers.get('content-type') ?? 'application/json'

		let body: FormData | URLSearchParams | string | undefined = undefined

		if (ct === 'multipart/form-data' || ct === 'application/x-www-form-urlencoded') {
			headers.delete('content-type')
			body = ct === 'multipart/form-data' ? new FormData() : new URLSearchParams()
			for (const [k, v] of Object.entries(opts.body as Record<string, string>)) {
				body.append(k, v)
			}
		}

		if (ct === 'application/json' && typeof opts.body !== 'string') {
			headers.set('content-type', 'application/json')
			body = JSON.stringify(opts.body)
		}

		const credentials = opts.credentials ?? 'include'
		const rep = await fetch(url.toString(), { method, ...opts, headers, body, credentials })
		if (!rep.ok) throw await this.ParseError(rep)

		const rs = await rep.text()
		try {
			return JSON.parse(rs) as T
		} catch (e) {
			return rs as unknown as T
		}
	}

	authForm = {
		getVkAuthPage: () => {
			return this.Fetch<string>('get', '/auth/vk', {})
		},

		authorizeAndGetAuthToken: () => {
			return this.Fetch<void>('post', '/auth/vk', {})
		},

		blankAuthPage: () => {
			return this.Fetch<string>('get', '/auth/blank.html', {})
		},
	}

	auth = {
		createAuthToken: (body: TokenRequest) => {
			return this.Fetch<AuthFragmentResponse>('post', '/api/auth/token', { body })
		},

		refreshAuthToken: () => {
			return this.Fetch<AuthFragmentResponse>('get', '/api/auth/refresh', {})
		},

		setAuthDataToSession: (body: TokenRequest) => {
			return this.Fetch<void>('post', '/api/auth/refresh', { body })
		},

		getUserProfile: () => {
			return this.Fetch<
				VkResponse & {
					response?: VkUserInfoResponse
				}
			>('get', '/api/auth/profile', {})
		},
	}

	playlist = {
		getFriskyRadio: () => {
			return this.Fetch<Tracklist>('get', '/api/playlist/frisky', {})
		},

		getFavorites: () => {
			return this.Fetch<Tracklist>('get', '/api/playlist/favorites', {})
		},

		getPlaylistTracks: () => {
			return this.Fetch<
				VkResponse & {
					response?: VkPlaylistResponse
				}
			>('get', '/api/playlist/', {})
		},
	}

	track = {
		getTrackById: (user_id: number, owner_id: number, id: number) => {
			return this.Fetch<void>('get', `/api/player/${user_id}/${owner_id}/${id}`, {})
		},

		addTrackInfo: (user_id: number, owner_id: number, id: number) => {
			return this.Fetch<void>('post', `/api/player/${user_id}/${owner_id}/${id}`, {})
		},

		editTrackInfo: (user_id: number, owner_id: number, id: number) => {
			return this.Fetch<void>('put', `/api/player/${user_id}/${owner_id}/${id}`, {})
		},
	}
}

export type AuthFragmentResponse = {
	user_id?: string
	access_token?: string
	secret?: string
	created?: string | null
	maxAge?: number | null
	expires?: string | null
	device_id?: string
}

export type AuthFragmentSession = {
	access_token?: string
	secret?: string
	user_id?: string
	device_id?: string
	created?: string | null
	maxAge?: number | null
	expires?: string | null
}

export type TokenRequest = {
	access_token?: string
	url?: string
	token?: string
	secret: string
	user_id?: string
	created?: string | null
	maxAge?: number | null
	expires?: string | null
}

export type TrackContent = {
	id?: number
	title?: string
	artist?: string
	duration?: number
	time_code?: string
	spotify?: string
	youtube?: string
	apple_music?: string
}

export type TrackItem = {
	id: number
	owner_id: number
	type: 'default' | 'dash' | 'hls' | 'smoothstreaming'
	url: string
	artwork?: string
	title: string
	artist: string
	date: number
	duration: number
	favorite?: boolean
	hidden?: boolean
	genre_list?: {
		id?: number
		name?: string
	}[]
	track_list?: TrackContent[]
	multipart?: boolean
	part_list?: {
		url?: string
		part?: number
		duration?: number
	}[]
}

export type Tracklist = {
	count: number
	offset: number
	total: number
	items: TrackItem[]
}

export type VkPlaylistResponse = {
	count: number
	items: {
		id: number
		owner_id: number
		artist: string
		title: string
		duration: number
		access_key?: string
		ads?: {
			content_id?: string
			duration?: string
			account_age_type?: string
			puid1?: string
			puid22?: string
		}
		is_explicit?: boolean
		is_focus_track?: boolean
		is_licensed?: boolean
		track_code?: string
		url: string
		date: number
		genre_id?: number
		short_videos_allowed?: boolean
		stories_allowed?: boolean
		stories_cover_allowed?: boolean
		like?: boolean
		content_restricted?: number
		album?: {
			id?: number
			title?: string
			owner_id?: number
			access_key?: string
			thumb?: {
				width?: number
				height?: number
				id?: string
				photo_34?: string
				photo_68?: string
				photo_135?: string
				photo_270?: string
				photo_300?: string
				photo_600?: string
				photo_1200?: string
			}
			main_color?: string
		}
		release_audio_id?: string
	}[]
}

export type VkResponse = {
	response?: VkPlaylistResponse | VkUserInfoResponse
}

export type VkUserInfoResponse = {
	profile?: {
		id?: number
		first_name?: string
		last_name?: string
		can_access_closed?: boolean
		is_closed?: boolean
	}
	info?: {
		'2fa_required'?: number
		audio_ads?: {
			day_limit?: number
			track_limit?: number
			types_allowed?: string[]
			sections?: string[]
		}
		audio_permissions?: {
			audio_meta_info?: boolean
		}
		business_notify_enabled?: number
		change_email_url?: string
		change_phone_url?: string
		country?: string
		debug_available?: boolean
		email?: string
		email_status?: string
		eu_user?: boolean
		feed_preloading?: {
			media_discover?: {
				on_app_start?: {
					enabled?: boolean
				}
			}
			breaking_news?: {
				on_app_start?: {
					enabled?: boolean
				}
				on_neighbour_tab?: {
					enabled?: boolean
				}
			}
		}
		https_required?: number
		intro?: number
		music_intro?: number
		fave_intro?: number
		menu_intro?: boolean
		community_comments?: boolean
		track_installed_apps?: boolean
		clickable_stickers?: {
			max_stickers?: {
				hashtag?: number
				mention?: number
				music?: number
				playlist?: number
				video?: number
				question?: number
				place?: number
				story_reply?: number
				owner?: number
				market_item?: number
				link?: number
				post?: number
				poll?: number
				sticker?: number
				app?: number
				situational_theme?: number
				spoiler?: number
			}
		}
		reports_spa?: boolean
		lang?: number
		money_p2p_params?: {
			min_amount?: number
			max_amount?: number
			currency?: string
			show_intro?: boolean
		}
		no_wall_replies?: number
		own_posts_default?: number
		phone?: string
		phone_status?: string
		profiler_enabled?: boolean
		profiler_settings?: {
			api_requests?: boolean
			download_patterns?: {
				type?: string
				pattern?: string
				probability?: number
				error_probability?: number
			}[]
		}
		raise_to_record_enabled?: boolean
		settings?: {
			available?: boolean
			forced?: boolean
			name?: string
			value?: string
		}[]
		support_url?: string
		valid_from?: {
			discover_posts?: number
			discover_categories?: number
		}
		vk_pay_endpoint?: string
		vk_pay_endpoint_v2?: string
		stream_special_comment_price?: number
		menu_ads_easy_promote?: {
			item_url?: string
			item_text?: string
			show_badge?: boolean
		}
		side_menu_custom_items?: {
			icon?: string
			title?: string
			action?: {
				type?: string
				target?: string
				url?: string
			}
		}[]
		subscription_combo_allowed?: boolean
		include_channel_notifications?: boolean
		messages_transcript_auto_show?: boolean
		messages_multiline_input?: boolean
		messages_translation_language_pairs?: string[]
		obscene_text_filter?: boolean
		messages_reaction_notifications?: {
			max_message_age_sec: number
			max_reactions: number
		}
		market_adult_18plus?: {
			is_adult_by_profile: boolean
			is_adult_confirm: boolean
		}
		can_change_password?: boolean
		is_personal_ads_easy_promote_enabled?: boolean
		messages_counter_settings?: {
			include_muted?: boolean
			include_group_dialogs?: boolean
			include_channels?: boolean
		}
	}
	time?: number
	has_new_items?: {
		global_promotion?: number
		store_new_items?: number
		stickers_version_hash?: string
		favorite_stickers_version_hash?: string
	}
	allow_buy_votes?: boolean
	ads_stoplist?: void[]
	use_vigo?: boolean
	html_games_supported?: number
	defaultAudioPlayer?: string
}
